export default {
  cafes: [
    {
      id: 1,
      name: 'У нас есть кофе',
      desc: 'Вкусный кофе всегда',
      subwayCode: 'Alexanders Garden',
      address: 'ул. Моховая, 11',
      workTime: '8:00 - 20:00',
      img: 'https://s.restorating.ru/w/1920x1080/articles/2886/None-109637.jpeg',
    },
    {
      id: 2,
      name: 'У кота',
      desc: 'Котики тоже любят кофе',
      subwayCode: 'Moscow',
      address: 'ул. Любителей котов, 11',
      workTime: '8:00 - 20:00',
      img: '',
    },
    {
      id: 3,
      name: 'И в хвост, и в гриву',
      desc: 'Устали кофе пить? Так не стоит пить',
      subwayCode: 'Alexanders Garden',
      address: 'ул. Безкофеиновая, 100',
      workTime: '8:00 - 20:00',
      img: 'https://img01.rl0.ru/afisha/1064x1064i/s4.afisha.ru/mediastorage/22/0c/4264de1d623d4a6dad3d3f700c22.jpg',
    },
    {
      id: 4,
      name: 'Откуда мы',
      desc: 'Как к нам добраться',
      subwayCode: 'Moscow',
      address: 'ул. Пушкина, д. Колотушкина',
      workTime: '8:00 - 20:00',
      img: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/3b/d4/c5/caption.jpg?w=600&h=-1&s=1',
    },
    {
      id: 5,
      name: 'Американо',
      desc: 'Сделаем Американо снова великим',
      subwayCode: 'Arbat',
      address: 'ул. Соединенных Штанов, 50',
      workTime: '8:00 - 20:00',
      img: 'https://img.restoclub.ru/uploads/place/8/4/6/1/84613fb8327108c62dd5882e213997a3_w470.jpg',
    },
    {
      id: 6,
      name: 'Другая кофейня',
      desc: 'Здесь могла быть ваша кофейня',
      subwayCode: 'Theatr',
      address: 'ул. Устал Придумывать, 11',
      workTime: '8:00 - 20:00',
      img: '',
    },
  ],
};
